using VeloXML.Application.Features.Documentos.Queries.GetDocumentos;

namespace VeloXML.Application.Features.Pedidos.Commands.CreatePedido;

public record PedidoItemDto(
    Guid Id,
    Guid ProdutoId,
    string Descricao,
    string Unidade,
    decimal Quantidade,
    decimal PrecoUnitario,
    decimal Desconto,
    decimal ValorTotal,
    string? Cfop,
    string? Ncm,
    decimal AliquotaIcms,
    decimal AliquotaPis,
    decimal AliquotaCofins,
    string? CstIcms,
    string? CstPis,
    string? CstCofins,
    int IcmsOrigem,
    string? IbsCbsCst,
    string? IbsCbsClassificacaoTributaria
);

public record PedidoDto(
    Guid Id,
    int Numero,
    Guid ClienteId,
    Guid DestinatarioId,
    string DestinatarioNome,
    string Status,
    string? Observacoes,
    decimal ValorTotal,
    DateTime CreatedAt,
    List<PedidoItemDto> Itens,
    string NaturezaOperacao,
    string FinalidadeEmissao,
    string ModalidadeFrete,
    DateTime? DataSaida,
    string? FormaPagamento,
    string? MeioPagamento,
    string? InformacoesComplementares,
    bool ConsumidorFinal,
    int PresencaComprador,
    decimal ValorFrete,
    decimal ValorSeguro,
    decimal ValorOutrasDespesas,
    Guid? DocumentoId,
    string? DocumentoNumero,
    string? DocumentoSerie,
    string? DocumentoChaveAcesso,
    string? DocumentoOrigem,
    string? DocumentoStatus,
    DateTime? DocumentoDataEmissao,
    string? DocumentoProtocoloAutorizacao,
    DateTime? DocumentoDataAutorizacao,
    string? DocumentoMotivoCancelamento,
    string? DocumentoProtocoloCancelamento,
    DateTime? DocumentoDataCancelamento,
    DocumentoImpostosDto? DocumentoImpostos
);
